### ISSUE TITLE
[REQUEST] Remove the "Executed by" footer

### ISSUE THREAD

**Issue by Syjalo** [Hypixel-Translators/hypixel-translators-bot#383]
In slash commands, you can see who used the command. I suggest to remove the "Executed by" footer.
![Безымянный](https://user-images.githubusercontent.com/62868468/123972577-68d4c200-d9d4-11eb-9bbf-faccb4294f09.png)

**Comment by ImRodry** [comment]
This was initially added as a way to always know who executed what command since you could previously delete your message but this does become obsolete with slash commands, you're right. The reason I'm not so sure what to do about this is that this ends up giving some customization to each command response and would bring up lots of inconsistencies. For example, if we were to remove the footer from the /language embed, we would have to remove the author's avatar as well but, in places where a footer is required (such as /help), would we have the author's avatar? Not to mention that the embed looks weird without anything at the bottom in my opinion.
![image](https://user-images.githubusercontent.com/38259440/123974548-94e04b00-d9b4-11eb-9a38-03ac9b9e492a.png)
I won't close this just yet as I need to think about this and discuss with the team, but I can't guarantee we'll adress this.

**Comment by ImRodry** [comment]
I know it has been a while since this issue was created but I finally have some news on it
After some discussion internally we have decided to do a complete overhaul of the tips system and this will be fixed on that overhaul.
We will now put tips in the footer of most commands and remove the random messages sent after commands, as well as the /tip command. This will apply to every command except those that have their own footer e.g. page numbers, etc. Most credit footers will also be removed as these were seen as redundant and often unfair.
If you have any feedback to give on this, feel free to let me know, otherwise this should be implemented in the next couple of days.
