### ISSUE TITLE
Cooldown on /hypixelverify

### ISSUE THREAD

**Issue by TreasonMay** [Hypixel-Translators/hypixel-translators-bot#743]
### Feature description

Cooldown is way too long - have to wait after being told what to do to verify, in order to verify.

### Alternative solutions

- Decrease the cooldown.
- Allow two or three attempts to verify before cooldown.

### Additional context

I wrote all of this during this cooldown, that's just how long it is.

**Comment by ImRodry** [comment]
The cooldown of 10 minutes on the hypixelverify command is intentional and will not change. This is because the API we use to fetch the data from Hypixel caches your data for 10 minutes after it was accessed, so if you change anything within that timeframe the bot wouldn’t know because the data would be outdated.

**Comment by TreasonMay** [comment]
Here's a suggestion then:
Use the official, uncached, Hypixel API just for this feature.

**Comment by ImRodry** [comment]
That is something I can consider since we don’t need any of the data transformations that slothpixel does, however we’d need to be careful not to hit ratelimits. You should open a different issue if you want to keep that tracked but I may end up doing it either way.
